

services:
  ubuntu_test:
    image: ubuntu-custom
    container_name: ubuntu_container
    privileged: true          # Enable privileged mode for systemd
    volumes:
      - ./src:/testSrc          # Mount local ./src to /testSrc in the container
    healthcheck:               # Add health check for SSH service
      test: ["CMD", "nc", "-z", "localhost", "22"]
      interval: 10s
      timeout: 5s
      retries: 3
